name: internship_sample
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.2
  debouncer_widget: ^1.0.0
  easy_image_viewer: ^1.4.0
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  persistent_bottom_nav_bar: ^5.0.2
  smooth_page_indicator: ^1.1.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/images/logos/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/assets/images/logos/company_logo.png
    - lib/core/assets/images/logos/app_logo.png
    - lib/core/assets/images/onboard_choose_products.png
    - lib/core/assets/images/onboard_make_payment.png
    - lib/core/assets/images/onboard_get_your_order.png

    - lib/core/assets/images/logos/google_logo.svg
    - lib/core/assets/images/logos/apple_logo.svg
    - lib/core/assets/images/logos/facebook_logo.svg
    - lib/core/assets/images/logos/visa_logo.svg
    - lib/core/assets/images/logos/paypal_logo.svg
    - lib/core/assets/images/logos/maestro_logo.svg
    - lib/core/assets/images/logos/apple_pay_logo.svg
    - lib/core/assets/images/other/payment_success.svg

    - lib/core/assets/images/get_started_bg_image.png

    - lib/core/assets/images/other/offer_image1.jpg

    - lib/core/assets/images/avatar.jpeg
    - lib/core/assets/images/home/heels.jpg
    - lib/core/assets/images/home/special_offer.png
    - lib/core/assets/images/other/special_offer.svg

    - lib/core/assets/images/home/yellow_bar.jpg
    - lib/core/assets/images/home/star.jpg
    - lib/core/assets/images/home/starbg.jpg
    - lib/core/assets/images/home/star_bg.svg

    - lib/core/assets/images/product_images/Cashew Apple Squash/Cashew apple
      squash.jpg
    - lib/core/assets/images/product_images/Cashew Pine Jam/Cashew pine jam.jpg

    - lib/core/assets/images/product_images/Cashew Powder/Cashew Powder 1.jpg
    - lib/core/assets/images/product_images/Cashew Powder/Cashew Powder 2.jpg
    - lib/core/assets/images/product_images/Cashew Powder/Cashew Powder 3.jpg
    - lib/core/assets/images/product_images/Cashew Powder/Cashew Powder 4.jpg

    - lib/core/assets/images/product_images/Cashew Soda/Cashew soda.jpg

    - lib/core/assets/images/product_images/Cashew Soup/Cashew Soup-mix .jpg
    - lib/core/assets/images/product_images/Cashew Soup/Cashew Soup.jpg

    - lib/core/assets/images/product_images/Cashew Vanilla MilkShake/Cashew
      Vanilla Milk Shake Powder.jpg

    - lib/core/assets/images/product_images/Cashew Vita/Cashew Vita.jpg

    - lib/core/assets/images/product_images/Cashew Vita Cardamom
      flavoured/Cashew vita cardamom flavoured.jpg

    - lib/core/assets/images/product_images/Cashew Vita Pistachio
      flavoured/Cashew vita Pistachio flavoured.jpg

    - lib/core/assets/images/product_images/Chilli Garlic/Chilly Garlic.jpg

    - lib/core/assets/images/product_images/Chilly Coated/Red Chilly Coated
      Cashew.jpg

    - lib/core/assets/images/product_images/Honey Coated/Honey Coated Cashew.jpg

    - lib/core/assets/images/product_images/Plain Cashew/Plain cashew (B).png
    - lib/core/assets/images/product_images/Plain Cashew/Plain Cashew (F).png
    - lib/core/assets/images/product_images/Plain Cashew/Plain cashew (B) bgwhite.png
    - lib/core/assets/images/product_images/Plain Cashew/Plain Cashew (F) bgwhite.png
    - lib/core/assets/images/product_images/Plain Cashew/Plain Cashew (F) nobg.png

    - lib/core/assets/images/product_images/Roasted and Salted Cashew/Roasted
      and salted Cashew.png
    - lib/core/assets/images/product_images/Roasted and Salted Cashew/Roasted and salted Cashew bgwhite.png

    - lib/core/assets/images/product_images/Salt and Pepper/Salt and Pepper.jpg

    - lib/core/assets/images/product_images/Cashew Plain2-600x600.jpg
    - lib/core/assets/images/home_icon.svg

    - lib/core/assets/images/product_images/Roasted.jpg

  # An image asset can refer to one or more resolution-specific "variants",
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LibreCaslonText
      fonts:
        - asset: fonts/LibreCaslonText-Regular.ttf
        - asset: fonts/LibreCaslonText-Bold.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
